name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./subiletbackend/subiletbackend.sln

      - name: Build
        run: dotnet build ./subiletbackend/subiletbackend.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test ./subiletbackend/subiletbackend.sln --no-build --configuration Release --verbosity normal

      - name: Build Docker image
        run: docker build -t subilet-backend:latest -f subiletbackend/Dockerfile .

      # - name: Push Docker image to registry (opsiyonel)
      #   run: |
      #     echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      #     docker tag subilet-backend:latest yourrepo/subilet-backend:latest
      #     docker push yourrepo/subilet-backend:latest 